name = "password-hashing"
type = "javascript"
compatibility_date = "2022-05-24"
account_id = "2dcc5a4f486a50625b4167e90d113158"
workers_dev = true
route = ""
zone_id = "" 

[build]
command = "npm run build"

[build.upload]
format = "modules"
main='index.js'